In [2]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

# Creating list to append tweet data to
tweets_list2 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('covid19 lang:ja since:2020-06-01 until:2020-06-10').get_items()):
    if i>4000:
        break
    tweets_list2.append([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.lang])
    
# Creating a dataframe from the tweets list above
tweets_df2 = pd.DataFrame(tweets_list2, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'lang'])

In [7]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

def getLanguageTweets(scrape_text):
    tweet_list=[]
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper(scrape_text).get_items()):
        if i>400:
            break
        tweet_list.append([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.lang])

    # Creating a dataframe from the tweets list above
    tweets_data = pd.DataFrame(tweet_list, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'lang'])
    return tweets_data
df1= getLanguageTweets('covid19 lang:ja since:2020-06-01 until:2020-06-10')

In [9]:
df1.head()

,Datetime,Tweet Id,Text,Username,lang
0,2020-06-09 23:59:10+00:00,1270505751459409920,#モーニングショー \nクラスター対策 … 濃厚接触者の追跡に過ぎないので … \n対策と呼...,nextpost,ja
1,2020-06-09 23:58:04+00:00,1270505473146421248,AKB48（日本）\nJKT48（インドネシア）\nBNK48（タイ）\nTPE48（台湾）...,ine1016Haro,ja
2,2020-06-09 23:57:46+00:00,1270505400266153984,これ、今回のCovid19に対して自分なりの対策でもあるんだよね。\n\nリモート私だけ禁止...,maccha1030,ja
3,2020-06-09 23:57:33+00:00,1270505344570015744,"＜全世界＞\n感染者数：7,311,526\n死者数：413,011\n退院者数：3,594...",corona_num_bot,ja
4,2020-06-09 23:57:09+00:00,1270505245295050752,#インド工科大学ハイテラバード校 @IITHyderabadと @IndiaBARC は、#...,IndianEmbTokyo,ja

In [6]:
# Creating list to append tweet data to
tweets_list_english = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('covid19 lang:en since:2020-06-01 until:2020-06-10').get_items()):
    if i>4000:
        break
    tweets_list_english.append([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.lang])
    
# Creating a dataframe from the tweets list above
tweets_df_en = pd.DataFrame(tweets_list_english, columns=['Datetime', 'Tweet Id', 'Text', 'Username','lang'])

In [40]:
# Creating list to append tweet data to
tweets_list_german = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('covid19 lang:de since:2020-06-01 until:2020-06-10').get_items()):
    if i>4000:
        break
    tweets_list_german.append([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.lang])
    
# Creating a dataframe from the tweets list above
tweets_df_de = pd.DataFrame(tweets_list_german, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'lang'])

In [42]:
# Creating list to append tweet data to
tweets_list_hindi = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('covid19 lang:hi since:2020-06-01 until:2020-06-10').get_items()):
    if i>4000:
        break
    tweets_list_hindi.append([tweet.date, tweet.id, tweet.content, tweet.user.username,tweet.lang])
    
# Creating a dataframe from the tweets list above
tweets_df_hi = pd.DataFrame(tweets_list_hindi, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'lang'])

In [ ]:
# Creating list to append tweet data to
tweets_list_french = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('covid19 lang:fr since:2020-06-01 until:2020-06-10').get_items()):
    if i>4000:
        break
    tweets_list_french.append([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.lang])
    
# Creating a dataframe from the tweets list above
tweets_df_fr = pd.DataFrame(tweets_list_french, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'lang'])

In [47]:
# Creating list to append tweet data to
tweets_list_spanish = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('covid19 lang:es since:2020-06-01 until:2020-06-10').get_items()):
    if i>4000:
        break
    tweets_list_spanish.append([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.lang])
    
# Creating a dataframe from the tweets list above
tweets_df_es = pd.DataFrame(tweets_list_spanish, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'lang'])

In [45]:
# Creating list to append tweet data to
tweets_list_chinese = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('covid19 lang:zh-cn since:2020-06-01 until:2020-07-10').get_items()):
    if i>4000:
        break
    tweets_list_chinese.append([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.lang])
    
# Creating a dataframe from the tweets list above
tweets_df_zh = pd.DataFrame(tweets_list_chinese, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'lang'])

In [50]:
frames = [tweets_df2, tweets_df_en, tweets_df_de, tweets_df_hi, tweets_df_fr, tweets_df_es, tweets_df_zh]

data_twitter = pd.concat(frames)

In [51]:
data_twitter.head()

,Datetime,Tweet Id,Text,Username,lang
0,2020-06-09 23:59:10+00:00,1270505751459409920,#モーニングショー \nクラスター対策 … 濃厚接触者の追跡に過ぎないので … \n対策と呼...,nextpost,ja
1,2020-06-09 23:58:04+00:00,1270505473146421248,AKB48（日本）\nJKT48（インドネシア）\nBNK48（タイ）\nTPE48（台湾）...,ine1016Haro,ja
2,2020-06-09 23:57:46+00:00,1270505400266153984,これ、今回のCovid19に対して自分なりの対策でもあるんだよね。\n\nリモート私だけ禁止...,maccha1030,ja
3,2020-06-09 23:57:33+00:00,1270505344570015744,"＜全世界＞\n感染者数：7,311,526\n死者数：413,011\n退院者数：3,594...",corona_num_bot,ja
4,2020-06-09 23:57:09+00:00,1270505245295050752,#インド工科大学ハイテラバード校 @IITHyderabadと @IndiaBARC は、#...,IndianEmbTokyo,ja

In [52]:
data_twitter = data_twitter.sample(frac = 1)

In [54]:
data_twitter

,Datetime,Tweet Id,Text,Username,lang
2866,2020-06-09 22:43:16+00:00,1270486651198898178,Sigh! @WHO walks back statement on Monday that...,KassandraTroy,en
2860,2020-06-13 16:40:16+00:00,1271844850824908800,#Taiwan 繼續小心\n#COVID19 還沒結束\nhttps://t.co/P1Qw...,HsuanHsieh1,zh
565,2020-06-09 14:04:25+00:00,1270356078916767745,Duniya Ka Mashoor Dariya Jahan Ab Bhi Gold Pay...,arznewsnetwork,hi
1330,2020-06-09 16:07:38+00:00,1270387086546423808,#ALGERIE #TransitionDemocratique #TAMAZIΓT(Off...,AlgeriaFaraDaSe,fr
719,2020-06-09 13:08:16+00:00,1270341948532862981,#Delhi के मुख्यमंत्री अरविंद केजरीवाल का #Covi...,Zee_Hindustan,hi
...,...,...,...,...,...
1423,2020-06-09 08:12:41+00:00,1270267559238086656,केंद्र के अधिकारियों का कहना है कि दिल्ली में ...,moresecreted,hi
3301,2020-06-10 01:13:19+00:00,1270524410642886657,据 #韩国 中央防疫对策本部10日通报，9日0时至24时，新增 #新型冠状病毒（#COVID...,NEWSPIMCHINA,zh
3465,2020-06-08 09:35:13+00:00,1269925943121936385,@CNNnews18 @ArvindKejriwal Ye mahan Insaan aaj...,GopalRathi1812,hi
2617,2020-06-09 12:06:55+00:00,1270326508465381377,L’ARPCE Congo participe au Forum de l’Union Af...,ARPCECongo,fr
1511,2020-06-09 23:04:47+00:00,1270492063046352896,"El Secretario Fidencio Romero Tobón, nos compa...",PRIdePUEBLA,es